config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'welcome', to: 'pages#registration', as: :welcome
  get 'contact', to: 'pages#contact'
  resources :products, only: [:index, :show]
  resources :messages, only: [:index, :new, :create] do
    collection do
      get 'by_product'
    end
  end
  namespace :suppliers do
    resources :verifications, only: [:edit, :update]
    resources :certifications, only: [:new, :create, :edit, :update]
    resources :licenses, only: [:new, :create, :destroy]
    resources :offers, only: [:show, :update] do
      member do
        get 'generateoffer', to: 'offers#generateoffer'
      end
    end
    resources :products, only: [:create, :new, :edit, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
  resources :suppliers, only: [:show, :edit, :update]
  namespace :purchasers do
    resources :offers, only: [:new, :show, :create, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  #validation
  PAYMENT = ["Visa", "MasterCard", "Invoice", "Wire Transfer"]

  belongs_to :user
  belongs_to :supplier
  has_many :product_offers, dependent: :destroy
  has_many :products, through: :product_offers

  validates :destination, :payment, presence: true
  validates :payment, inclusion: { in: PAYMENT }

  def self.add_product(user, product, amount, offer_attributes)
    return if user.supplier?
    offer = offer_for_product(user, product)
    offer.assign_attributes(offer_attributes)

    ActiveRecord::Base.transaction do
      offer.save!
      ProductOffer.create!(product: product, offer: offer, amount: amount.to_i)
      offer.calculate_price
    end
    return offer
  end

  def self.offer_for_product(user, product)
    offer = self.find_or_initialize_by(
      confirmed: false,
      user: user,
      supplier: product.supplier
    )
  end

  def calculate_price
    prices = product_offers.map { |po| po.product.price.to_i * po.amount.to_i }
    self.update(price: prices.sum)
  end
end

app/controllers/purchasers/dashboard_controller.rb
class Purchasers::DashboardController < ApplicationController
  # we don't use policy_scoped here; no associated model
  skip_after_action :verify_policy_scoped

  def index
    @user = current_user
    authorize @user, policy_class: Purchasers::DashboardPolicy
  end
end

app/controllers/purchasers/dashboards_controller.rb
class Purchasers::DashboardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/purchasers/offers_controller.rb
class Purchasers::OffersController < ApplicationController
  before_action :find_offer, only: [:show, :destroy, :update]

  def show
    # policy_class: app/policies/purchasers/offer_policy#show
    authorize([:purchasers, @offer])
  end

  def new
    @product = Product.find(params[:product_id])
    @offer = Offer.offer_for_product(current_user, @product)
    # policy_class: app/policies/purchasers/offer_policy#create
    authorize([:purchasers, @offer])
  end

  def create
    @product = Product.find(params[:offer][:product_id])
    @offer = Offer.add_product(current_user, @product, product_offer_params[:amount], offer_params)
    authorize([:purchasers, @offer])
    if @offer.id
      flash[:alert] = "Offer submitted successfully!"
      redirect_to purchasers_offer_path(@offer)
    else
      render :new
    end
  end

  def update
    @offer.update(offer_confirmed_params)
    # policy_class: app/policies/suppliers/offer_policy#show
    authorize([:purchasers, @offer])
    redirect_to purchasers_offer_path(@offer)
    # create

  end

  def destroy
    @offer.destroy
    # policy_class: app/policies/offer_policy#destroy
    authorize([:purchasers, @offer])
    redirect_to purchasers_dashboard_path
  end

  private

  def find_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:destination, :payment)
  end

  def offer_confirmed_params
    params.permit(:confirmed)
  end

  def product_offer_params
    params.require(:offer).require(:product_offer).permit(:amount)
  end
end

app/controllers/suppliers/offers_controller.rb
class Suppliers::OffersController < ApplicationController
  before_action :find_offer, only: [:show,:update,:generateoffer]

  def show
    # policy_class: app/policies/suppliers/offer_policy#show
    authorize([:suppliers, @offer])
  end



  def update
    @offer.update(offer_params)
    # policy_class: app/policies/suppliers/offer_policy#show
    @offer.update(approved_date: Time.now)
    authorize([:suppliers, @offer])
    redirect_to suppliers_offer_path(@offer)
  end

  def rejected
    # policy_class: app/policies/suppliers/offer_policy#show
    authorize([:suppliers, @offer])
    @offer.rejected
    @offer.update
  end

  def generateoffer
    authorize([:suppliers, @offer])
    @user = current_user
    # policy_class: app/policies/suppliers/offer_policy#show
    html = render_to_string(:generateoffer => "generateoffer.html.erb",:layout => false)
    kit = PDFKit.new(html, :page_size => 'Letter')
    kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/pages/suppliers/offers/_generateoffer.scss"
    kit.to_pdf
    send_data(kit.to_pdf, :filename => "quote_#{@user.name}.pdf", :type => "application/pdf")
  end


  private

  def find_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.permit(:approved)
  end
end

app/views/purchasers/offers/new.html.erb
<div class="container">
  <div class="row">
    <%# <div class="col-xs-12 col-sm-4 col-offset-6"> %>
    <div class="form">
      <h1>Offer for: <%= @product.name %></h1>
      <h6><small><%= @product.supplier.name %></small></h6>
      <%= simple_form_for @offer, url: purchasers_offers_path, method: :POST  do |f| %>
        <div class="form-inputs">
          <%= f.input :destination, disabled: @offer.id.present? %>
          <%= f.input :payment , collection: Offer::PAYMENT, prompt: :translate, disabled: @offer.id.present? %>
          <%= f.simple_fields_for :product_offer do |ff|  %>
            <%= ff.input :amount , label: 'Quantity:'%>
          <% end %>
          <%= f.hidden_field :product_id, :value => @product.id %>
        </div>
        <div class="d-flex justify-content-between align-items-center ml-auto", style="width:28%">
          <div>
            <%= link_to "Cancel", product_path(@product), class: "btn btn-outline-secondary" %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, :value => "Send offer", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    <%# </div> %>
  </div>
</div>

app/views/purchasers/offers/show.html.erb
<div class="row d-flex justify-content-center">
  <h1>Preview Offer</h1>
</div>

<div class="offer-container my-5">
  <div class="row">
    <% if @offer.approved.nil? %>
      <%= link_to "Back to Products", products_path, :class => "btn btn-outline-dark mx-3", :id => "btn-browse" %>
      <h3><small>Status: Pending</small></h3>
    <% elsif @offer.approved.present? %>
      <h3><small>Status: Approved</small></h3>
    <% end %>
  </div>

  <div class="row text-align-left my-5" style="width: 50%;">
    <dt class="col-sm-3">Destination</dt>
    <dd class="col-sm-9"><%= @offer.destination %></dd>
    <dt class="col-sm-3">Payment</dt>
    <dd class="col-sm-9"><%= @offer.payment %></dd>
    <dt class="col-sm-3">Supplier</dt>
    <dd class="col-sm-9"><%= @offer.supplier.name %></dd>
    <dt class="col-sm-3">Quantity</dt>
    <dd class="col-sm-9"><%= @offer.product_offers.sum("CAST(COALESCE(amount, '0') AS DECIMAL)").round %></dd>
    <dt class="col-sm-3">Total Price</dt>
    <dd class="col-sm-9">$<%= @offer.price %></dd>
  </div>

  <div class="row flex-column justify-content-center my-5">
    <% if @offer.products.empty? %>
      Products may have been removed from platform, please contact <%= @offer.supplier.name %> for more information.
    <% else %>
      <% @offer.products.uniq.each do |product| %>
        <%= render partial: 'shared/cards/product_card', locals: { product: product } %>
      <% end %>
    <% end %>
  </div>

  <div class="row d-flex ml-auto my-2 mx-2">
    <% if @offer.approved.nil? %>
      <% if @offer.confirmed.blank? %>
        <%= link_to 'Delete Offer', purchasers_offer_path(@offer.id), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-lg btn-outline-danger mx-3" %>
        <div class="ml-auto">
          <%= link_to "Cancel", products_path, :class => "btn btn-lg btn-outline-secondary mx-3", :id => "btn-browse" %>
          <%= link_to 'Submit Offer', purchasers_offer_path(@offer, confirmed: true), method: :put, :class =>"btn btn-lg btn-success mx-3" %>
        </div>
      <% end %>
    <% elsif @offer.approved.present? %>
      <h6>Your offer has been approved</h6>
    <% else %>
      <p>Your request has been rejected</p>
    <% end %>
  </div>
</div>