config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'welcome', to: 'pages#registration', as: :welcome
  get 'contact', to: 'pages#contact'
  resources :products, only: [:index, :show]
  resources :messages, only: [:index, :new, :create] do
    collection do
      get 'by_product'
    end
  end
  namespace :suppliers do
    resources :verifications, only: [:edit, :update]
    resources :certifications, only: [:new, :create, :edit, :update]
    resources :licenses, only: [:new, :create, :destroy]
    resources :offers, only: [:show, :update] do
      member do
        get 'generateoffer', to: 'offers#generateoffer'
      end
    end
    resources :products, only: [:create, :new, :edit, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
  resources :suppliers, only: [:show, :edit, :update]
  namespace :purchasers do
    resources :offers, only: [:new, :show, :create, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  #validation

  DELIVERYTERM = ["FOB", "EXW", "FAS", "FCA", "CFR", "CPT", "CIF", "CIP", "DES", "DAF", "DEQ", "DDP", "DDU"]
  PAYMETTERM = ["T/T", "L/C", "D/P", "Western Union", "Moneygram"]

  belongs_to :user
  has_many :products, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :licenses, dependent: :destroy
  has_many :verifications, dependent: :destroy
  has_one_attached :photo
  validates :delivery_terms, inclusion: { in: DELIVERYTERM, allow_blank: true }
  validates :payment_terms, inclusion: { in: PAYMETTERM, allow_blank: true }

  def information_complete?
    delivery_terms.present? && payment_terms.present? && fei_number.present?
  end

  def name_and_profile_match?
    return true if Cecv.find_by(name: name)&.fei_number == self.fei_number

    self.errors.add(:base, "No matching CECV database entry found.")
    false
  end



  def create_verification
    Verification.create!(
      supplier: self,
      registration_completion: true
    )
  end

  def license_check
    self.verifications.first&.update(valid_registration_license: true)
  end

end

app/controllers/purchasers/dashboard_controller.rb
class Purchasers::DashboardController < ApplicationController
  # we don't use policy_scoped here; no associated model
  skip_after_action :verify_policy_scoped

  def index
    @user = current_user
    authorize @user, policy_class: Purchasers::DashboardPolicy
  end
end

app/controllers/purchasers/dashboards_controller.rb
class Purchasers::DashboardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/suppliers/certifications_controller.rb
class Suppliers::CertificationsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:new, :edit]
  before_action :find_certification, only: [:edit,:update]


  def new
    @certification = Certification.new
    @product = Product.find(params[:product_id])
    authorize([:suppliers, @certification])
  end

  def create
    @certification = Certification.new(certification_params)
    @product = Product.find(params[:certification][:product_id])
    @certification.products << @product
    authorize([:suppliers, @certification])
    if @certification.save
      redirect_to suppliers_dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @certification.update(certification_params)
      redirect_to products_path
    else
      render :edit
    end
  end



  private

  def find_certification
    @certification = Certification.find(params[:id])
  end

  def certification_params
    params.require(:certification).permit(:number, :category, :listing_number, :code, :start_date, :expired_date, :authority, photos: [])
  end
end

app/controllers/suppliers/dashboard_controller.rb
class Suppliers::DashboardController < ApplicationController
  # we don't use policy_scoped here; no associated model
  skip_after_action :verify_policy_scoped

  def index
    @user = current_user
    @supplier = Supplier.find_by(user: current_user)
    
    # policy_class: app/policies/suppliers/dashboard_policy#index
    authorize @supplier, policy_class: Suppliers::DashboardPolicy

  end
end

app/controllers/suppliers/dashboards_controller.rb
class Suppliers::DashboardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/suppliers/licenses_controller.rb
class Suppliers::LicensesController < ApplicationController

  def new
    @license = License.new
    @supplier = current_user.supplier
    authorize @license
  end

  def create
    @license = License.new(license_params)
    @supplier = Supplier.find_by(user: current_user)
    @license.supplier = @supplier
    authorize @license

    if @license.save && @supplier.verifications.first&.valid_registration_license
      redirect_to suppliers_dashboard_path, notice: 'Your license was successfully created.'
    elsif @license.save
      @supplier.license_check
      redirect_to suppliers_dashboard_path, notice: 'Your license was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @license = License.find(params[:id])
    authorize @license
    @license.destroy
    redirect_to suppliers_dashboard_path
  end

  private

  def license_params
    params.require(:license).permit(:authority, :number, :start_date, :expired_date, photos: [])
  end
end

app/controllers/suppliers/offers_controller.rb
class Suppliers::OffersController < ApplicationController
  before_action :find_offer, only: [:show,:update,:generateoffer]

  def show
    # policy_class: app/policies/suppliers/offer_policy#show
    authorize([:suppliers, @offer])
  end



  def update
    @offer.update(offer_params)
    # policy_class: app/policies/suppliers/offer_policy#show
    @offer.update(approved_date: Time.now)
    authorize([:suppliers, @offer])
    redirect_to suppliers_offer_path(@offer)
  end

  def rejected
    # policy_class: app/policies/suppliers/offer_policy#show
    authorize([:suppliers, @offer])
    @offer.rejected
    @offer.update
  end

  def generateoffer
    authorize([:suppliers, @offer])
    @user = current_user
    # policy_class: app/policies/suppliers/offer_policy#show
    html = render_to_string(:generateoffer => "generateoffer.html.erb",:layout => false)
    kit = PDFKit.new(html, :page_size => 'Letter')
    kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/pages/suppliers/offers/_generateoffer.scss"
    kit.to_pdf
    send_data(kit.to_pdf, :filename => "quote_#{@user.name}.pdf", :type => "application/pdf")
  end


  private

  def find_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.permit(:approved)
  end
end

app/controllers/suppliers/products_controller.rb
class Suppliers::ProductsController < ApplicationController
  before_action :find_product, only: [:edit,:update, :destroy]
  def new
    @product = Product.new
    authorize([:suppliers, @product])
  end

  def create
    @product = Product.new(product_params)
    supplier = Supplier.find_by(user: current_user)
    @product.supplier = supplier
    if @product.save
      authorize([:suppliers, @product])
      redirect_to new_suppliers_certification_path(product_id: @product.id)
    else
      render :new
    end
  end

  def edit
    authorize([:suppliers, @product])
  end

  def update
    if @product.update(product_params)
      authorize([:suppliers, @product])
      redirect_to suppliers_dashboard_path
    else
      render :new
    end
  end

  def destroy
    @product.destroy
    authorize([:suppliers, @product])
    redirect_to suppliers_dashboard_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :category, :production_quantity,:minimum_order_quantity, photos: [])
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/suppliers/verifications_controller.rb
class Suppliers::VerificationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:edit]
  def edit
  end

  def update
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :find_supplier, only: [:show,:edit,:update]

  def show
    authorize @supplier
  end

  def edit
    authorize @supplier
  end

  def update
    authorize @supplier
    @supplier.update(supplier_params)

    if  @supplier.name_and_profile_match? && @supplier.verifications.exists? # already exists
      redirect_to suppliers_dashboard_path
    elsif @supplier.name_and_profile_match? && @supplier.verifications.empty? # new user
      @supplier.create_verification
      redirect_to suppliers_dashboard_path
    else
      render :edit
    end
  end


  private

  def supplier_params
    params.require(:supplier).permit(:name, :location, :industry,
                                     :delivery_terms, :payment_terms, :fei_number,
                                     :nearest_port, :established, :photo)
  end

  def find_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/views/suppliers/dashboard/index.html.erb
<div class="dashboard d-flex" style="min-height: 100vh; max-width: 100%;">
  <div class="left-col col-xs-12 col-md-3">
    <div class="profile-img ">
      <% if @user.supplier.photo.attached?  %>
        <%= cl_image_tag @user.supplier.photo.key, height: 150, width: 200, crop: :fill %>
      <% else %>
        <%= cl_image_tag("https://res.cloudinary.com/demyxeys9/image/upload/v1592292947/veracity/avatar-png-1_wblzc1.png", :width => 240, :height => 240) %>
      <% end %>
    </div>
    <div class="left-info">
      <div class="company-info">
        <div class="company-header d-flex justify-content-between">
          <h5>My Company</h5>
          <%= link_to "Edit", edit_supplier_path(@user.supplier), :class => "btn btn-outline-secondary" %>
        </div>
        <hr>
        <p>Name: <%= @user.supplier.name %></p>
        <p>Location: <%= @user.supplier.location %></p>
        <p>Email: <%= @user.email %></p>
      </div>
      <div class="licenses-info">
        <div class="license-header d-flex justify-content-between">
          <h5>Licenses</h5>
          <%= link_to "Add", new_suppliers_license_path, :class => "btn btn-outline-secondary" %>
        </div>
        <hr>
        <% @user.supplier.licenses.each do |license| %>
          <div class="license">
            <p>Authority: <%= license.authority %></p>
            <p>Number: <%= license.number %></p>
            <% if license.photos.attached?  %>
              <% license.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill %>
              <% end %>
            <% else %>
              <%= image_tag "sample_license.jpg", height: 150, width: 200, crop: :fill %>
            <% end %>
            <%= link_to "Delete", suppliers_license_path(license), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-outline-warning mx-2"  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="right-col col-xs-12 col-md-9">
    <div class="top-info d-flex row">
      <div class="header-name">
        <% if @user.supplier.verifications.exists? && @user.supplier.verifications.first.registration_completion && @user.supplier.verifications.first.valid_registration_license  %>
          <h1><%= @user.name%> <%= icon('far', 'check-circle') %></h1>
        <% else %>
          <h1><%= @user.name%> <%= icon('far', 'times-circle') %></h1>
        <% end %>
        <sub id="subtag">Supplier</sub>
      </div>
      <div class="header-name">
        <%= link_to "Add product", new_suppliers_product_path, :class => "btn btn-lg btn-success mx-2" %>
      </div>
    </div>
    <!-- verfication status check -->
    <div class="status-check">
      <% if @user.supplier.verifications.exists? && @user.supplier.verifications.first.registration_completion && @user.supplier.verifications.first.valid_registration_license  %>
        <h4><%= icon('fas', 'check') %> VeraCity Verification complete. Welcome to our community!</h4>
        <div class="progress">
          <div class="progress-bar bg-primary" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Profile Complete!</div>
        </div>
      <% elsif @user.supplier.verifications.exists? && @user.supplier.verifications.first.registration_completion  %>
        <%= link_to new_suppliers_license_path do%>
          <p>Next step - Add licenses</p>
        <% end %>
        <div class="progress">
          <div class="progress-bar bg-info" role="progressbar" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75% | Completed profile</div>
        </div>
      <% else %>
        <%= link_to edit_supplier_path(@user.supplier) do%>
          <p>Next step - Complete company profile</p>
        <% end %>
        <div class="progress">
          <div class="progress-bar bg-warning" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
        </div>
      <% end %>
    </div>
    <div class="nav-pills-dashboard">
      <!-- tabs -->
      <ul class="nav nav-tabs nav-justified">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="pills-products-tab" data-toggle="tab" href="#products" role="tab" aria-controls="pills-products" aria-selected="true">My Products</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="pills-pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pills-pending" aria-selected="false">Pending Offers — <%= current_user.supplier.offers.where(approved: nil).count %></a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="pills-closed-tab" data-toggle="tab" href="#closed" role="tab" aria-controls="pills-closed" aria-selected="false">Closed Offers — <%= current_user.supplier.offers.where.not(approved: nil).count %></a>
        </li>
      </ul>
      <!-- tab contents -->
      <div class="tab-content" id="myTabContent">
        <!-- My Products-->
        <div class="tab-pane show active" id="products" role="tabpanel" aria-labelledby="products-tab">
          <div class="d-flex flex-wrap flex-fill justify-content-between">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Category</th>
                  <th scope="col">Price/unit</th>
                  <th scope="col">Certification</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @user.supplier.products.each do |p| %>
                  <%= link_to product_path(p) do %>
                    <tr>
                      <td><%= p.name %></td>
                      <td><%= p.category %></td>
                      <td>$<%= p.price %></td>
                      <% p.certifications.each do |c|  %>
                        <td><%= c.category %></td>
                      <% end %>
                      <td>
                        <%= link_to "Add Certifictions", new_suppliers_certification_path(product_id: p.id), class: "btn btn-info" %>
                        <%= link_to "Edit", edit_suppliers_product_path(p), class: "btn btn-warning" %>
                        <%= link_to "Delete", suppliers_product_path(p), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <!-- Pending Offers -->
        <div class="tab-pane" id="pending" role="tabpanel" aria-labelledby="pending-tab">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Destination</th>
                <th scope="col">Products</th>
                <th scope="col">Payment</th>
                <th scope="col">Total price</th>
                <th scope="col">Detail</th>
              </tr>
            </thead>
            <tbody>
              <% @user.supplier.offers.each do |offer| %>
                <%  if offer.approved.nil?  %>
                  <%= link_to suppliers_offer_path(offer) do %>
                    <tr>
                      <td><%= offer.destination %></td>
                      <td>
                        <% offer.products.each do |p| %>
                          <p> <%= p.name %>
                            $<%= p.price %> </p>
                        <% end %>
                      </td>
                      <td><%= offer.payment %></td>
                      <td><%= offer.price %></td>
                      <td><%= link_to "Detail", suppliers_offer_path(offer), class: "btn btn-info" %></td>
                    </tr>
                  <% end %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- Closed Offers -->
        <div class="tab-pane" id="closed" role="tabpanel" aria-labelledby="closed-tab">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Destination</th>
                <th scope="col">Products</th>
                <th scope="col">Payment</th>
                <th scope="col">Total price of offer</th>
                <th scope="col">Detail</th>
              </tr>
            </thead>
            <tbody>
              <% @user.supplier.offers.each do |offer| %>
                <%  unless offer.approved.nil? %>
                  <!-- use present to condition -->
                  <%= link_to suppliers_offer_path(offer) do %>
                    <tr>
                      <td><%= offer.destination %></td>
                      <td>
                        <% offer.products.each do |p| %>
                          <p> <%= p.name %>
                            $<%= p.price %> </p>
                        <% end %>
                      </td>
                      <td><%= offer.payment %></td>
                      <td><%= offer.price %></td>
                      <td><%= link_to "Detail", suppliers_offer_path(offer), class: "btn btn-info" %></td>
                    </tr>
                  <% end %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <!-- pills dashboard-->
    </div>
    <!-- right col -->
  </div>
  <!-- full dashboard-->