config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'welcome', to: 'pages#registration', as: :welcome
  get 'contact', to: 'pages#contact'
  resources :products, only: [:index, :show]
  resources :messages, only: [:index, :new, :create] do
    collection do
      get 'by_product'
    end
  end
  namespace :suppliers do
    resources :verifications, only: [:edit, :update]
    resources :certifications, only: [:new, :create, :edit, :update]
    resources :licenses, only: [:new, :create, :destroy]
    resources :offers, only: [:show, :update] do
      member do
        get 'generateoffer', to: 'offers#generateoffer'
      end
    end
    resources :products, only: [:create, :new, :edit, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
  resources :suppliers, only: [:show, :edit, :update]
  namespace :purchasers do
    resources :offers, only: [:new, :show, :create, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-container-half">
    <h1>Trusted Suppliers</h1>
    <h1>From us to you.</h1>
    <p>We know choosing a vendor is hard. We're here to help.</p>
    <% unless user_signed_in? %>
      <a href="/welcome" class="btn btn-lg btn-dark" style="border-radius:4px;">Become a member</a>
    <% else %>
      <a href="/products" class="btn btn-lg btn-dark" style="border-radius:4px;">Browse products</a>
    <% end %>
    <%# <%= render 'shared/signup_bar' %>
    <%# <a class="btn btn-primary" href="/users/sign_in">Begin your search</a> %>
  </div>
</div>

app/views/shared/_breadcrumb.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to "< Back", :back %></li>
  </ol>
</nav>

app/views/shared/_button.html.erb
<div>
  <button type="button" class="btn btn-primary">Primary</button>
</div>


<div>
  <button type="button" class="btn btn-primary btn-sm">Small button</button>
</div>

<div>
  <button type="button" class="btn btn-primary btn-lg">Large button</button>
</div>

app/views/shared/_cards.html.erb
<div class="card-category">
  <h6><%= step %></h6>
  <p class="card-text"><%= info %></p>
  <img src=<%= img %> alt="image for step">
</div>

app/views/shared/_dashboard_button.html.erb
<a class="btn btn-dashboard" href="/purchasers/dashboard" role="button">Dashboard</a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_jiayou.html.erb
<div class="jiayou">
    <h4><strong>Stay safe</strong></h4>
</div>

app/views/shared/_message_form.html.erb
<div class="row form">
  <div class="col-xs-12 col-sm-8 offset-sm-2 my-2">
    <%# <h1>Send a Message</h1> %>
    <%= simple_form_for @message do |f| %>
      <div class="form-inputs">
        <%= f.input :title, label: "Subject" %>
        <%= f.input :content, label: "Body" %>
        <%= f.hidden_field :product_id, :value => product_id %>
        <%= f.hidden_field :receiver_id, :value => receiver_id %>
        <%= f.hidden_field :sender_id, :value => current_user.id %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, value: "Send Message" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_message_modal.html.erb
<!-- Modal -->
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">To: <%= product.supplier.name %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render partial: 'shared/message_form', locals: { product_id: product.id, receiver_id: receiver_id } %>
        </div>
        <div class="modal-footer">
          <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Send</button> %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-veracity">
  <div class="navbar-left">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>
  <div class="navbar-right">
    <% if user_signed_in? %>
      <%= link_to "About", about_path, class: "nav-link" %>
      <%= link_to "Products", products_path, class: "nav-link" %>
      <%= link_to "Contact Us", contact_path, class: "nav-link" %>
      <% if current_user.user_type == "supplier"%>
        <% if current_user.supplier.photo.attached?  %>
          <%= cl_image_tag current_user.supplier.photo.key, id: "navbarDropdown", class: "avatar-img", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag("https://res.cloudinary.com/demyxeys9/image/upload/v1592292947/veracity/avatar-png-1_wblzc1.png", id: "navbarDropdown", class: "avatar-img", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% end %>
      <% else %>
        <%= cl_image_tag("https://res.cloudinary.com/demyxeys9/image/upload/v1592292947/veracity/avatar-png-1_wblzc1.png", id: "navbarDropdown", class: "avatar-img", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if current_user.user_type == "supplier"%>
          <%= link_to "Dashboard", suppliers_dashboard_path, class: "dropdown-item" %>
        <% else %>
          <%= link_to "Dashboard", purchasers_dashboard_path, class: "dropdown-item" %>
        <% end  %>
        <%= link_to "Inbox", messages_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    <% else %>
      <%= link_to "About", about_path, class: "nav-link" %>
      <%= link_to "Contact Us", contact_path, class: "nav-link" %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <%= link_to "Register", welcome_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_offer_product_card.html.erb
<%= link_to product_path(product) do %>
  <div class="card-product">
    <% if product.photos.attached?  %>
      <% product.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    <% else %>
      <%= image_tag "mask.jpg" %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= product.name %></h2>
      <p>Price: $<%= product.price %>/unit</p>
      <p>Category: <%= product.category %></p>
    </div>
  </div>
<% end %>

app/views/shared/_search 1.html.erb
<div class="search">
  <form action="#">
    <input type="email" id="your-email" placeholder="face mask">
    <button class="button" type="submit" class="btn btn-gradient">
      <i class="fas fa-search"></i> Search
    </button>
  </form>
</div>



<div class="Signup">
  <form action="#">
  <input type="email" id="your-email" placeholder="bob@gmail.com">
  <input class="button" type="submit" value="Sign up free">
  </form>
</div>

app/views/shared/_signup_bar.html.erb
<div class="signup">
  <form action="/users/sign_up">
  <input type="email" id="your-email" placeholder="bob@gmail.com">
  <input class="btn btn-signup" type="submit" value="Join now">
  </form>
</div>

app/views/shared/_terms_condition.html.erb
<div class="container px-2 py-2">
  <h5>Terms and Conditions for http://veracity.asia/</h5>
  <h6>Introduction</h6>
  <p>These Website Standard Terms and Conditions written on this webpage shall manage your use of our website, VeraCity accessible at http://veraccity.asia/.
    These Terms will be applied fully and affect to your use of this Website. By using this Website, you agreed to accept all terms and conditions written in here. You must not use this Website if you disagree with any of these Website Standard Terms and Conditions. These Terms and Conditions have been generated with the help of the Terms And Conditions Template and the Terms and Conditions Generator.
    Minors or people below 18 years old are not allowed to use this Website.</p>
  <h6>Intellectual Property Rights</h6>
  <p>Other than the content you own, under these Terms, http://veracity.asia/ and/or its licensors own all the intellectual property rights and materials contained in this Website.
    You are granted limited license only for purposes of viewing the material contained on this Website.</p>
  <h6>Restrictions</h6>
  <p>You are specifically restricted from all of the following:
    publishing any Website material in any other media;
    selling, sublicensing and/or otherwise commercializing any Website material;
    publicly performing and/or showing any Website material;
    using this Website in any way that is or may be damaging to this Website;
    using this Website in any way that impacts user access to this Website;
    using this Website contrary to applicable laws and regulations, or in any way may cause harm to the Website, or to any person or business entity;
    engaging in any data mining, data harvesting, data extracting or any other similar activity in relation to this Website;
    using this Website to engage in any advertising or marketing.
    Certain areas of this Website are restricted from being access by you and http://usesafewatch.com/ may further restrict access by you to any areas of this Website, at any time, in absolute discretion. Any user ID and password you may have for this Website are confidential and you must maintain confidentiality as well.</p>
  <h6>Your Content</h6>
  <p>In these Website Standard Terms and Conditions, “Your Content” shall mean any audio, video text, images or other material you choose to display on this Website. By displaying Your Content, you grant http://usesafewatch.com/ a non-exclusive, worldwide irrevocable, sub licensable license to use, reproduce, adapt, publish, translate and distribute it in any and all media.
    Your Content must be your own and must not be invading any third-party’s rights. http://usesafewatch.com/ reserves the right to remove any of Your Content from this Website at any time without notice.</p>
  <h6>Your Privacy</h6>
  <p>Please read Privacy Policy.
    No warranties
    This Website is provided “as is,” with all faults, and http://usesafewatch.com/ express no representations or warranties, of any kind related to this Website or the materials contained on this Website. Also, nothing contained on this Website shall be interpreted as advising you.</p>
  <h6>Limitation of liability</h6>
  <p>In no event shall http://vearcity.asia/, nor any of its officers, directors and employees, shall be held liable for anything arising out of or in any way connected with your use of this Website whether such liability is under contract.  http://vearcity.asia/, including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.
    <h6> Indemnification</h6>
    <p> You hereby indemnify to the fullest extent http://vearcity.asia/ from and against any and/or all liabilities, costs, demands, causes of action, damages and expenses arising in any way related to your breach of any of the provisions of these Terms.</p>
    <h6>   Severability</h6>
    <p>  If any provision of these Terms is found to be invalid under any applicable law, such provisions shall be deleted without affecting the remaining provisions herein.</p>
    <h6>Variation of Terms</h6>
    <p>  http://vearcity.asia/ is permitted to revise these Terms at any time as it sees fit, and by using this Website you are expected to review these Terms on a regular basis.</p>
    <h6>   Assignment</h6>
    <p>  The http://vearcity.asia/ is allowed to assign, transfer, and subcontract its rights and/or obligations under these Terms without any notification. However, you are not allowed to assign, transfer, or subcontract any of your rights and/or obligations under these Terms.
      Entire Agreement</p>
  </p>
   These Terms constitute the entire agreement between http://vearcity.asia/ and you in relation to your use of this Website, and supersede all prior agreements and understandings.
  Governing Law & Jurisdiction
  These Terms will be governed by and interpreted in accordance with the laws of the State of ca, and you submit to the non-exclusive jurisdiction of the state and federal courts located in ca for the resolution of any disputes.</p>
</div>