config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'welcome', to: 'pages#registration', as: :welcome
  get 'contact', to: 'pages#contact'
  resources :products, only: [:index, :show]
  resources :messages, only: [:index, :new, :create] do
    collection do
      get 'by_product'
    end
  end
  namespace :suppliers do
    resources :verifications, only: [:edit, :update]
    resources :certifications, only: [:new, :create, :edit, :update]
    resources :licenses, only: [:new, :create, :destroy]
    resources :offers, only: [:show, :update] do
      member do
        get 'generateoffer', to: 'offers#generateoffer'
      end
    end
    resources :products, only: [:create, :new, :edit, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
  resources :suppliers, only: [:show, :edit, :update]
  namespace :purchasers do
    resources :offers, only: [:new, :show, :create, :update, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # valdation
  CATEGORY = ["Mask","Thermometer","Bandage", "Isolation Gown","Medical First Aid Kit", "Face shield", "Gloves"]
  belongs_to :supplier
  has_many :product_offers,  dependent: :destroy
  has_many :offers, through: :product_offers

  has_and_belongs_to_many :certifications, dependent: :destroy
  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :certifications
  has_many_attached :photos

  validates :name, :price, :production_quantity, :minimum_order_quantity, presence: true
  validates :category, inclusion: { in: CATEGORY }

  #selection variable

  $category = ["Mask","thermometer","Bandage"]
  $minimum_order_quantity = ["100","200","300"]
  $certification = ["CE", "FDA", "ISO"]
  #pgsearch
  #for general search
  include PgSearch::Model
  pg_search_scope :search_by_name_certification,
    against: [:name, :category],
  associated_against: {
    certifications: [:category, :number]
  },
  using: {
    tsearch: { prefix: true}
  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @products = policy_scope(Product).order('updated_at ASC')
    @query = params[:query]

    if @query.present?
      @products = @products.search_by_name_certification(@query)
    end

  end

  def show
    @product = Product.find(params[:id])
    @message = Message.new
    @receiver = @product.supplier.user
    authorize @product
    # raise
  end

  private

  def filter_params
    params.require(:filter).permit(:category => [], :minimum_order_quantity => [], :certifications => {})
  end

end

app/controllers/suppliers/products_controller.rb
class Suppliers::ProductsController < ApplicationController
  before_action :find_product, only: [:edit,:update, :destroy]
  def new
    @product = Product.new
    authorize([:suppliers, @product])
  end

  def create
    @product = Product.new(product_params)
    supplier = Supplier.find_by(user: current_user)
    @product.supplier = supplier
    if @product.save
      authorize([:suppliers, @product])
      redirect_to new_suppliers_certification_path(product_id: @product.id)
    else
      render :new
    end
  end

  def edit
    authorize([:suppliers, @product])
  end

  def update
    if @product.update(product_params)
      authorize([:suppliers, @product])
      redirect_to suppliers_dashboard_path
    else
      render :new
    end
  end

  def destroy
    @product.destroy
    authorize([:suppliers, @product])
    redirect_to suppliers_dashboard_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :category, :production_quantity,:minimum_order_quantity, photos: [])
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/views/products/index.html.erb
<div class="row" style="justify-content: center;">
  <div class="search-box my-5">
    <%= form_tag products_path, class: "d-flex", method: :get do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-inline form-control",
            placeholder: "Search by Product name or Certification type" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="container d-flex justify-content-between">
  <div class="side-col">
    <h1>Filter</h1>
    <div class="filter-container">
      <%= simple_form_for :filter, url: products_path, method: "GET", remote: true, html: { id: "filter-form" } do |f| %>
        <%= f.input :category, label: "Product Type", collection: $category, as: :check_boxes %>
        <%= f.input :minimum_order_quantity, label: "minimum order", collection: $minimum_order_quantity, as: :check_boxes %>
        <%= f.fields_for :certifications do |s| %>
          <%= s.input :category, label: "Certification", collection: $certification, as: :check_boxes %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mid-col">
    <% @products.each do |product| %>
      <%= render :partial => 'shared/cards/product_card', locals: {:product => product } %>
    <% end %>
  </div>
  <div class="side-col">
    <h5><em>Most Viewed</em></h5>
    <% @products[0..7].reverse_each do |p| %>
      <div class="img-product">
        <%= link_to product_path(p) do %>
          <% p.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 100, width: 100, crop: :fill %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/products/index.js.erb
const replaceProducts = (innerHTML) => {
    const products = document.getElementById('products');
    products.innerHTML = innerHTML;
}

if ('<%= @filter %>' === "[]") {
    replaceProducts("<%= j render 'shared/product_card', products: Product.all %>")
} else {
    replaceProducts("<%= j render 'shared/product_card', products: @products %>")
}

app/views/products/show.html.erb
<!-- product info -->
<div class="container">
  <div class="row my-4">
    <h1 class="display-4"><%= @product.name %></h1>
  </div>
  <div class="product-container bg-light d-flex align-self-center my-5" >
    <div class="bd-highlight">
      <div id="arouselExampleControls" style="height: 400px; width: 400px; "class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% if @product.photos.attached?  %>
            <% @product.photos.each do |photo| %>
              <div class="carousel-item active">
                <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
              </div>
            <% end %>
          <% else %>
            <%= image_tag("mask.jpg", style: "height: 400px; width: 400px;") %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="product-show p-3 d-flex flex-column justify-content-between flex-fill">
      <div class="product-header">
        <h4>Product Detail</h4>
        <p><em>Some information about the product here</em></p>
      </div>
      <dl class="row description-list">
        <dt class="col-sm-3">Category</dt>
        <dd class="col-sm-9"><%= @product.category %></dd>
        <dt class="col-sm-3">Certification</dt>
        <dd class="col-sm-9">
          <% @product.certifications.each do |certification| %>
            <p><%= certification.category %></p>
          <% end %>
        </dd>
        <dt class="col-sm-3">Minimum Order</dt>
        <dd class="col-sm-9"><%= @product.minimum_order_quantity %> <small>units</small></dd>
        <dt class="col-sm-3">Price (per unit)</dt>
        <dd class="col-sm-9">$<%= @product.price %>.00 <small>USD</small></dd>
        <dt class="col-sm-3">In Stock</dt>
        <dd class="col-sm-9"><%= @product.production_quantity %> <small>units</small></dd>
        <% unless @product.supplier_id == current_user.supplier&.id %>
          <dt class="col-sm-3 text-truncate">Supplier</dt>
          <dd class="col-sm-9">
            <div type="button" class="btn btn-sm btn-outline-primary">
              <%= link_to "View #{@product.supplier.name} >", supplier_path(@product.supplier) %>
            </div>
          </dd>
        <% end %>
      </dl>
      <div class="row action-buttons">
        <div class="button-group d-flex">
          <div class="buttons align-items-end">
            <% if current_user.purchaser? %>
              <button type="button" class="btn btn-lg btn-outline-secondary" data-toggle="modal" data-target="#exampleModal">
                Send Message
                <%# <%= icon('far', 'envelope') %>
              </button>
            <% end %>
            <%= render 'shared/message_modal', product: @product, receiver_id: @product.supplier.user_id %>
            <% if current_user.purchaser? %>
              <div>
                <%= link_to "Make an Offer", new_purchasers_offer_path(product_id: @product.id), class: "btn btn-lg btn-primary" %>
              </div>
            <% end %>
            <% if policy([:suppliers, @product]).edit? %>
              <div><%= link_to "Edit product", edit_suppliers_product_path(@product), class: "btn btn-primary" %></div>
            <% end %>
            <% if policy([:suppliers, @product]).destroy? %>
              <div><%= link_to "Destroy product", suppliers_product_path(@product.id), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>